sudo: false
language: ruby
before_install: gem install bundler -v 1.14.1

rvm:
  - 2.1.5
  - 2.2.3
  - 2.3.0
  - 2.4.0

gemfile:
  - gemfiles/Gemfile.4.2.mysql2
  - gemfiles/Gemfile.5.0.pg

matrix:
  exclude:
    - gemfile: gemfiles/Gemfile.5.0.pg
      rvm: 2.1.5

before_script:
  - psql -c 'create database mygem_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS mygem_test;'

cache: bundler

notifications:
  email:
    - developers@expectedbehavior.com

install:
  # Replace default Travis CI bundler script with a version that doesn't
  # explode when lockfile doesn't match recently bumped version
  - gem uninstall bundler -x -I
  - gem install bundler --version='=1.12.5'
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script: bundle exec rake current_rspec