sudo: false
language: ruby

rvm:
  - 2.1.5
  - 2.2.3
  - 2.3.0
  - 2.4.0

gemfile:
  - gemfiles/Gemfile.4.2.sidekiq-4
  - gemfiles/Gemfile.5.0.pg
  - gemfiles/Gemfile.dalli_not_memcached
  - gemfiles/Gemfile.minimal

matrix:
  exclude:
    - gemfile: gemfiles/Gemfile.5.0.pg
      rvm: 2.1.5

before_install:
  - gem update bundler
  - psql -c 'create database metrician_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS metrician_test;'

cache: bundler

notifications:
  email:
    - developers@expectedbehavior.com

script: bundle exec rake current_rspec

services:
  - mysql
  - postgresql
  - redis-server
  - memcached
